version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mysqldb
    volumes:
      - ./src:/app/src

  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: userapi
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

