version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mysqldb
    volumes:
      - ./src:/app/src

  mysqldb:
    image: mysql
    restart: always
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

